### ISSUE TITLE
File tree isn't updated by Kanban notes.

### ISSUE THREAD

**Issue by Ruminov** [makary-s/obsidian-metafolders#1]
### What happened?
The metafolders file tree is automatically updated when I click/focus a normal note, but it doesn't work with the Kanban notes that I intend to use as parents; the file tree remains in the last non-kanban note (while interacting with the Kanban note).

### Expected behavior
Kanban notes should automatically trigger the file tree update just like normal notes do.

**Comment by CoffeeDrinkRabbit** [comment]
+1

**Comment by makary-s** [comment]
@Ruminov @CoffeeDrinkRabbit I'll try to fix it this week

**Comment by makary-s** [comment]
@Ruminov @CoffeeDrinkRabbit  Fixed in version 1.1.3. Is everything okay?

**Comment by Ruminov** [comment]
Now it works like a charm, thank you.
